[package]
name = "vaden-frontend"
version = "0.1.0"
edition = "2021"
authors = ["Łukasz Wojtów <lukasz.wojtow@gmail.com>"]
license = "AGPL-3.0"


[dependencies]
yew = { git = "https://github.com/yewstack/yew/", features = ["csr"], tag = "yew-v0.21.0"}